language: ruby
cache: bundler
sudo: false
rvm: 2.3.3

notifications:
  email: false

install:
  - pip3 install -r script/requirements.txt
  - python3 script/deployment-setup.py
  - script/bootstrap

script:
  - script/cibuild

# deploy staging to gh_pages branch
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: staging

# TODO deploy master to Union servers
