language: ruby
cache: bundler
sudo: false
rvm: 2.3.3

notifications:
  email: false

install:
  - pip install -r script/requirements.txt
  - python script/deployment-setup.py
  - script/bootstrap

script:
  - script/cibuild

# TODO deploy master to Union servers
