language: ruby

cache: bundler

sudo: false

rvm: 2.3.3

notifications:
  email: false

before_install:
- openssl aes-256-cbc -K $encrypted_3934c5b080f0_key -iv $encrypted_3934c5b080f0_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- eval `ssh-agent`
- chmod 600 deploy_rsa
- ssh-add deploy_rsa

install:
- pip install -r script/requirements.txt
- python script/deployment-setup.py
- script/bootstrap

script:
- script/cibuild

deploy:
- provider: script
  script: "rsync -av -e \"ssh -o StrictHostKeyChecking=no -o ForwardAgent=yes cunion@sshgw.ic.ac.uk ssh mly15@dougal.union.ic.ac.uk\" _site/ :/website/scc/cu"
  on:
    branch: master

