title: Imperial College Christian Union # your site title
author: Imperial College Christian Union
email: cu@imperial.ac.uk # email for form submission, you also have to change it in _js/scripts.js
description: > # this means to ignore newlines until "baseurl:"
  The Christian Union at Imperial College London is a student society which aims
  to give every student at Imperial an opportunity to hear about and respond to
  the good news of Jesus Christ.
baseurl: "/" # the subpath of your site, e.g. /blog TODO: remove this when deploying to Union servers
url: "" #"http://iccu.co.uk" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: CU_Imperial # replace with your_twitter_username or comment to remove link from footer
#github_username:  janczizikow # replace with your_github_username or comment to remove link from footer
instagram_username: ic_christian_union # replace with your_instagram_username or comment to remove link from footer
facebook_username: imperialcu
youtube_username: imperialcu
social:
  name: Imperial College Christian Union
  links:
    - https://twitter.com/CU_Imperial
    - https://www.facebook.com/imperialcu
    - https://instagram.com/ic_christian_union

# Build settings
markdown: kramdown
highlighter: rouge # or pygments or null
remote_theme: jekyll-sleek
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

prose:
  ignore:
    - README.md
    - .babelrc
    - .eslintignore
    - .eslintrc
    - .gitignore
    - .scss-lint.yml
    - .travis.yml
    - Gemfile
    - LICENSE.txt
    - gulpfile.js
    - jekyll-sleek.gemspec
    - package-lock.json
    - package.json
    - sw.js
    - _js/
  site: https://staging.iccu.co.uk
  media: assets/img/
  metadata:
    ".":
      - name: layout
        field:
          element: hidden
          value: page
      - name: title
        field:
          element: text
          label: Title of the page
      - name: permalink
        field:
          element: text
          label: type: /title-as-one-word/
